server:
  port: 8085

spring:
  application:
    name: payment-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/veridian_payments}
    username: ${SPRING_DATASOURCE_USERNAME:veridian}
    password: ${SPRING_DATASOURCE_PASSWORD:veridian_secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
